project:
  type: website

website:
  title: 'ResBaz Arizona'
  navbar:
    background: dark
    foreground: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - none
      - theme.scss
    resources:
      - styles
      - images
      - data
    toc: true
