project:
  type: website

website:
  title: 'ResBaz Arizona'
  navbar:
    background: dark
    foreground: primary
    left:
      - href: index.qmd
        text: Home
      - href: whoWeAre.qmd
        text: Who We Are

format:
  html:
    theme:
      - none
      - theme.scss
    resources:
      - styles
      - img
      - data
    toc: true
